name: flutter_modular
description: Smart project structure with dependency injection and route management
version: 3.3.1
homepage: https://github.com/Flutterando/modular

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_modular_annotations: ^0.0.2
  triple: ">=1.0.0 <2.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.3.1
  mockito: ^5.0.3
  flutter_test:
    sdk: flutter

flutter:
