name: flutter_modular
description: Smart project structure with dependency injection and route management
version: 6.3.0
homepage: https://github.com/Flutterando/modular

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  modular_core: ">=3.3.0 <4.0.0"
  meta: ">=1.3.0 <2.0.0"
  result_dart: ">=1.0.4 <2.0.0"
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutterando_analysis: ^0.0.2
  mocktail: ^0.3.0
  flutter_test:
    sdk: flutter


flutter:
