name: modular_test
description: Smart project structure with dependency injection and route management
version: 1.0.1+1
homepage: https://github.com/Flutterando/modular

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  modular_core: ">=1.0.0+2 <2.0.0"

dev_dependencies:
  test: ^1.17.10