name: modular_core
description: Smart project structure with dependency injection and route management
version: 1.1.5
homepage: https://github.com/Flutterando/modular

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  characters: ">=1.1.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"
  modular_interfaces: ">=1.0.4 <2.0.0"

dev_dependencies:
  test: ^1.17.10
