name: modular_core
description: Smart project structure with dependency injection and route management
version: 3.0.1+1
homepage: https://github.com/Flutterando/modular

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_injector: ">=1.1.0+4 <2.0.0"
  characters: ">=1.1.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"

dev_dependencies:
  flutterando_analysis: ^0.0.2
  test: ">=1.16.0 <2.0.0"
